//! Auto-generated by `datalink_shim_sqlite_dynlink_emit::emit_dynlink`
//! (Phase A, opaque-blob scalar dispatch). Do NOT edit by hand — regenerate.
#![allow(unused_imports, dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "bridge",
        generate_all,
    });
}

use bindings::exports::sqlite::extension::metadata::{
    Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
};
use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
use bindings::sqlite::extension::types::{FunctionFlags, SqlValue};

use bindings::compose::dynlink::linker;

const PROVIDER_ID: &str = "postgis_sfcgal-composed";
const EXTENSION_ROOT: &str = "postgis";
const CATALOG_EXTENSION: &str = "postgis";
const CATALOG_VERSION: &str = "0.1.0";

fn resolve() -> Result<linker::Instance, String> {
    linker::resolve_by_id(&PROVIDER_ID.to_string())
        .map_err(|e| format!("dynlink resolve('{}'): {:?}", PROVIDER_ID, e))
}

// -----------------------------------------------------------
// CBOR envelope (mirrors provider crate's Request/Response).
// -----------------------------------------------------------

#[derive(Debug, Clone)]
enum CborValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<CborValue>),
}

impl serde::Serialize for CborValue {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        match self {
            CborValue::Null => s.serialize_unit(),
            CborValue::Bool(b) => s.serialize_bool(*b),
            CborValue::Int(i) => s.serialize_i64(*i),
            CborValue::Float(f) => s.serialize_f64(*f),
            CborValue::Text(t) => s.serialize_str(t),
            CborValue::Bytes(b) => s.serialize_bytes(b),
            CborValue::List(items) => {
                use serde::ser::SerializeSeq;
                let mut seq = s.serialize_seq(Some(items.len()))?;
                for item in items {
                    seq.serialize_element(item)?;
                }
                seq.end()
            }
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
struct Request {
    #[serde(rename = "v")]
    version: u32,
    args: Vec<CborValue>,
}

#[derive(Debug, Clone, serde::Deserialize)]
struct Response {
    #[serde(default)]
    ok: Option<ResponseValue>,
    #[serde(default)]
    err: Option<String>,
}

#[derive(Debug, Clone)]
enum ResponseValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<ResponseValue>),
}

impl<'de> serde::Deserialize<'de> for ResponseValue {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{Error, MapAccess, SeqAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = ResponseValue;
            fn expecting(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
                f.write_str("a CBOR value (null, bool, int, float, text, bytes, list)")
            }
            fn visit_unit<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_none<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_bool<E: Error>(self, v: bool) -> Result<ResponseValue, E> { Ok(ResponseValue::Bool(v)) }
            fn visit_i64<E: Error>(self, v: i64) -> Result<ResponseValue, E> { Ok(ResponseValue::Int(v)) }
            fn visit_u64<E: Error>(self, v: u64) -> Result<ResponseValue, E> {
                if v <= i64::MAX as u64 { Ok(ResponseValue::Int(v as i64)) }
                else { Err(E::custom("u64 overflow to i64")) }
            }
            fn visit_f64<E: Error>(self, v: f64) -> Result<ResponseValue, E> { Ok(ResponseValue::Float(v)) }
            fn visit_str<E: Error>(self, v: &str) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v.to_string())) }
            fn visit_string<E: Error>(self, v: String) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v)) }
            fn visit_bytes<E: Error>(self, v: &[u8]) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v.to_vec())) }
            fn visit_byte_buf<E: Error>(self, v: Vec<u8>) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v)) }
            fn visit_seq<A: SeqAccess<'de>>(self, mut s: A) -> Result<ResponseValue, A::Error> {
                let mut items = Vec::new();
                while let Some(v) = s.next_element::<ResponseValue>()? { items.push(v); }
                Ok(ResponseValue::List(items))
            }
            fn visit_map<A: MapAccess<'de>>(self, mut m: A) -> Result<ResponseValue, A::Error> {
                let k: Option<String> = m.next_key()?;
                let k = k.ok_or_else(|| A::Error::custom("empty map"))?;
                let v = match k.as_str() {
                    "Null" => { let _: serde::de::IgnoredAny = m.next_value()?; ResponseValue::Null }
                    "Bool" => ResponseValue::Bool(m.next_value()?),
                    "Int"  => ResponseValue::Int(m.next_value()?),
                    "Float" => ResponseValue::Float(m.next_value()?),
                    "Text" => ResponseValue::Text(m.next_value()?),
                    "Bytes" => {
                        let b: serde_bytes::ByteBuf = m.next_value()?;
                        ResponseValue::Bytes(b.into_vec())
                    }
                    "List" => ResponseValue::List(m.next_value()?),
                    other => return Err(A::Error::custom(format!("unknown tag: {}", other))),
                };
                Ok(v)
            }
        }
        d.deserialize_any(V)
    }
}

fn encode_request(args: Vec<CborValue>) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    ciborium::into_writer(&Request { version: 1, args }, &mut out)
        .map_err(|e| format!("cbor encode: {}", e))?;
    Ok(out)
}

fn decode_response(bytes: &[u8]) -> Result<Response, String> {
    ciborium::from_reader(bytes).map_err(|e| format!("cbor decode: {}", e))
}

fn call(method: &str, args: Vec<CborValue>) -> Result<ResponseValue, String> {
    let inst = resolve()?;
    let payload = encode_request(args)?;
    let bytes = inst
        .invoke(&method.to_string(), &payload)
        .map_err(|e| format!("{}: invoke: {:?}", method, e))?;
    let resp = decode_response(&bytes)?;
    if let Some(err) = resp.err {
        return Err(format!("{}: {}", method, err));
    }
    Ok(resp.ok.unwrap_or(ResponseValue::Null))
}

// -----------------------------------------------------------
// SqlValue marshalling — variant discipline per the @1.0.0
// contract. The `wit-value` arm is Phase-A-out-of-scope; the
// bridge treats it as null in both directions.
// -----------------------------------------------------------

fn sqlv_to_cbor(v: &SqlValue) -> Result<CborValue, String> {
    Ok(match v {
        SqlValue::Null => CborValue::Null,
        SqlValue::Integer(i) => CborValue::Int(*i),
        SqlValue::Real(f) => CborValue::Float(*f),
        SqlValue::Text(t) => CborValue::Text(t.clone()),
        SqlValue::Blob(b) => CborValue::Bytes(b.clone()),
        // WitValue is Phase-A-out-of-scope. Prior code silently
        // downgraded it to CBOR null, which lied to the provider
        // (an explicit-typed argument became indistinguishable
        // from a real NULL). Surface an explicit error instead so
        // callers see a diagnostic on the SQL side.
        SqlValue::WitValue(_) => {
            return Err("bridge: WitValue arg not supported in dynlink Phase A".to_string());
        }
    })
}

fn response_to_sqlv(v: ResponseValue) -> Result<SqlValue, String> {
    Ok(match v {
        ResponseValue::Null => SqlValue::Null,
        ResponseValue::Bool(b) => SqlValue::Integer(if b { 1 } else { 0 }),
        ResponseValue::Int(i) => SqlValue::Integer(i),
        ResponseValue::Float(f) => SqlValue::Real(f),
        ResponseValue::Text(t) => SqlValue::Text(t),
        ResponseValue::Bytes(b) => SqlValue::Blob(b),
        // A list-shaped response has no SQLite scalar sqlvalue
        // arm. Prior code silently returned SqlValue::Null, hiding
        // a shape mismatch behind an implicit NULL. Return an
        // explicit error so the SQL side sees a diagnostic.
        ResponseValue::List(_) => {
            return Err("bridge: list-shaped response not supported".to_string());
        }
    })
}

fn scalar_name_by_id(id: u64) -> Option<&'static str> {
    match id {
        1 => Some("cg_constrained_delaunay_triangles"),
        2 => Some("cg_polygon_repair"),
        3 => Some("cg_threed_alpha_wrapping"),
        4 => Some("st_3darea"),
        5 => Some("st_alpha_shape"),
        6 => Some("st_approx_convex_partition"),
        7 => Some("st_buffer_threed"),
        8 => Some("st_convex_hull_threed"),
        9 => Some("st_convexhullthreed"),
        10 => Some("st_coord_dim_threed"),
        11 => Some("st_difference_threed"),
        12 => Some("st_differencethreed"),
        13 => Some("st_exterior_ring_threed"),
        14 => Some("st_extrude"),
        15 => Some("st_extrude_polygon_straight_skeleton"),
        16 => Some("st_extrude_straight"),
        17 => Some("st_extrude_straight_skeleton"),
        18 => Some("st_force_lhr"),
        19 => Some("st_force_valid"),
        20 => Some("st_geometry_n_threed"),
        21 => Some("st_geometry_type_threed"),
        22 => Some("st_greene_approx_convex_partition"),
        23 => Some("st_has_validity_flag"),
        24 => Some("st_interior_ring_n_threed"),
        25 => Some("st_intersection_threed"),
        26 => Some("st_intersectionthreed"),
        27 => Some("st_is_empty_threed"),
        28 => Some("st_is_planar"),
        29 => Some("st_is_solid"),
        30 => Some("st_is_threed"),
        31 => Some("st_is_valid_detail_threed"),
        32 => Some("st_is_valid_threed"),
        33 => Some("st_line_substring"),
        34 => Some("st_linesubstring"),
        35 => Some("st_make_solid"),
        36 => Some("st_minimum_bounding_sphere_center"),
        37 => Some("st_minimum_bounding_sphere_radius"),
        38 => Some("st_minkowski_sum"),
        39 => Some("st_minkowskisum"),
        40 => Some("st_num_geometries_threed"),
        41 => Some("st_num_interior_rings_threed"),
        42 => Some("st_num_points_threed"),
        43 => Some("st_offset_polygon"),
        44 => Some("st_optimal_alpha_shape"),
        45 => Some("st_optimal_convex_partition"),
        46 => Some("st_orientable_surface"),
        47 => Some("st_orientation"),
        48 => Some("st_point_m_threed"),
        49 => Some("st_point_n_threed"),
        50 => Some("st_point_x_threed"),
        51 => Some("st_point_y_threed"),
        52 => Some("st_point_z_threed"),
        53 => Some("st_rotate_x"),
        54 => Some("st_rotate_y"),
        55 => Some("st_rotate_z"),
        56 => Some("st_rotatex"),
        57 => Some("st_rotatey"),
        58 => Some("st_rotatez"),
        59 => Some("st_round"),
        60 => Some("st_scale_threed_around_center"),
        61 => Some("st_simplify_preserve_topology_threed"),
        62 => Some("st_simplify_threed"),
        63 => Some("st_straight_skeleton"),
        64 => Some("st_straight_skeleton_distance"),
        65 => Some("st_straight_skeleton_partition"),
        66 => Some("st_straightskeleton"),
        67 => Some("st_tesselate"),
        68 => Some("st_union_threed"),
        69 => Some("st_unionthreed"),
        70 => Some("st_visibility_point"),
        71 => Some("st_visibility_segment"),
        72 => Some("st_volume"),
        73 => Some("st_y_monotone_partition"),
        _ => None,
    }
}

/// SQL-name aliasing: translate a compact-form SQL name (e.g.
/// `st_geomfromtext`) to its WIT-canonical (long) form
/// (`st_geom_from_text`) before kebab-casing to the provider
/// method name. The catalog carries both spellings as scalars in
/// `leaf.scalars` (both are advertised via `metadata.describe()`
/// so callers can use either), and as first-class `[[aliases]]`
/// entries. The provider dispatch only matches the WIT-canonical
/// form; the bridge's per-row `call` calls `canonical_for(name)`
/// so both spellings route to the same provider arm.
fn canonical_for(name: &str) -> &str {
    match name {
            "st_convexhullthreed" => "st_convex_hull_threed",
            "st_differencethreed" => "st_difference_threed",
            "st_intersectionthreed" => "st_intersection_threed",
            "st_linesubstring" => "st_line_substring",
            "st_minkowskisum" => "st_minkowski_sum",
            "st_rotatex" => "st_rotate_x",
            "st_rotatey" => "st_rotate_y",
            "st_rotatez" => "st_rotate_z",
            "st_straightskeleton" => "st_straight_skeleton",
            "st_unionthreed" => "st_union_threed",
        other => other,
    }
}

// -----------------------------------------------------------
// Guest impls.
// -----------------------------------------------------------

struct Component;

impl MetadataGuest for Component {
    fn describe() -> Manifest {
        let scalar_functions: Vec<ScalarFunctionSpec> = vec![
            ScalarFunctionSpec {
                id: 1,
                name: "cg_constrained_delaunay_triangles".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 2,
                name: "cg_polygon_repair".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 3,
                name: "cg_threed_alpha_wrapping".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 4,
                name: "st_3darea".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 5,
                name: "st_alpha_shape".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 6,
                name: "st_approx_convex_partition".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 7,
                name: "st_buffer_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 8,
                name: "st_convex_hull_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 9,
                name: "st_convexhullthreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 10,
                name: "st_coord_dim_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 11,
                name: "st_difference_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 12,
                name: "st_differencethreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 13,
                name: "st_exterior_ring_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 14,
                name: "st_extrude".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 15,
                name: "st_extrude_polygon_straight_skeleton".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 16,
                name: "st_extrude_straight".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 17,
                name: "st_extrude_straight_skeleton".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 18,
                name: "st_force_lhr".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 19,
                name: "st_force_valid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 20,
                name: "st_geometry_n_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 21,
                name: "st_geometry_type_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 22,
                name: "st_greene_approx_convex_partition".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 23,
                name: "st_has_validity_flag".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 24,
                name: "st_interior_ring_n_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 25,
                name: "st_intersection_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 26,
                name: "st_intersectionthreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 27,
                name: "st_is_empty_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 28,
                name: "st_is_planar".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 29,
                name: "st_is_solid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 30,
                name: "st_is_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 31,
                name: "st_is_valid_detail_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 32,
                name: "st_is_valid_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 33,
                name: "st_line_substring".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 34,
                name: "st_linesubstring".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 35,
                name: "st_make_solid".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 36,
                name: "st_minimum_bounding_sphere_center".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 37,
                name: "st_minimum_bounding_sphere_radius".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 38,
                name: "st_minkowski_sum".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 39,
                name: "st_minkowskisum".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 40,
                name: "st_num_geometries_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 41,
                name: "st_num_interior_rings_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 42,
                name: "st_num_points_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 43,
                name: "st_offset_polygon".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 44,
                name: "st_optimal_alpha_shape".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 45,
                name: "st_optimal_convex_partition".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 46,
                name: "st_orientable_surface".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 47,
                name: "st_orientation".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 48,
                name: "st_point_m_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 49,
                name: "st_point_n_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 50,
                name: "st_point_x_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 51,
                name: "st_point_y_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 52,
                name: "st_point_z_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 53,
                name: "st_rotate_x".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 54,
                name: "st_rotate_y".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 55,
                name: "st_rotate_z".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 56,
                name: "st_rotatex".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 57,
                name: "st_rotatey".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 58,
                name: "st_rotatez".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 59,
                name: "st_round".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 60,
                name: "st_scale_threed_around_center".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 61,
                name: "st_simplify_preserve_topology_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 62,
                name: "st_simplify_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 63,
                name: "st_straight_skeleton".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 64,
                name: "st_straight_skeleton_distance".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 65,
                name: "st_straight_skeleton_partition".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 66,
                name: "st_straightskeleton".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 67,
                name: "st_tesselate".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 68,
                name: "st_union_threed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 69,
                name: "st_unionthreed".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 70,
                name: "st_visibility_point".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 71,
                name: "st_visibility_segment".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 72,
                name: "st_volume".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 73,
                name: "st_y_monotone_partition".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
        ];
        Manifest {
            name: EXTENSION_ROOT.to_string(),
            version: CATALOG_VERSION.to_string(),
            scalar_functions,
            aggregate_functions: vec![],
            collations: vec![],
            vtabs: vec![],
            dot_commands: vec![],
            has_authorizer: false,
            has_update_hook: false,
            has_commit_hook: false,
            has_wal_hook: false,
            wal_hook_id: 0,
            declared_capabilities: vec![],
            optional_capabilities: vec![],
            preferred_prefix: None,
            prefix_expansion: None,
            typed_values: vec![],
        }
    }
}

impl ScalarFunctionGuest for Component {
    fn call(func_id: u64, args: Vec<SqlValue>) -> Result<SqlValue, String> {
        let name = scalar_name_by_id(func_id)
            .ok_or_else(|| format!("unknown function id {}", func_id))?;
        // SQL-style null propagation. Providers that need to
        // observe explicit NULL arguments will need a follow-up
        // Phase to opt in per-arm.
        if args.iter().any(|v| matches!(v, SqlValue::Null)) {
            return Ok(SqlValue::Null);
        }
        // Alias translation: SQL name → WIT-canonical → provider
        // method (kebab-case). Compact-form SQL names (e.g.
        // `st_geomfromtext`) route through `canonical_for` to their
        // long form (`st_geom_from_text`) before kebab-casing;
        // non-alias names pass through unchanged. See
        // `canonical_for` above.
        let canonical = canonical_for(name);
        let method = canonical.replace('_', "-");
        let cbor_args: Vec<CborValue> = args
            .iter()
            .map(sqlv_to_cbor)
            .collect::<Result<Vec<_>, String>>()?;
        let resp = call(&method, cbor_args)?;
        response_to_sqlv(resp)
    }
}

bindings::export!(Component with_types_in bindings);
